# Generated by Django 3.2a1 on 2023-12-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_auto_20231216_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
