# Generated by Django 3.2a1 on 2023-12-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_auto_20231220_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='number_rating',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
