# Generated by Django 3.2a1 on 2023-12-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_auto_20231220_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reating',
            new_name='rating',
        ),
    ]
